// Generated by CoffeeScript 1.3.1
(function() {
  var Blob, Game, game, io;

  Game = require('./game.js').Game;

  Blob = require('./game.js').Blob;

  io = require('socket.io').listen(8080);

  game = new Game();

  game.start_game();

  setInterval(function() {
    return game.compute_state();
  }, Game.UPDATE_INTERVAL);

  setInterval(function() {
    return game.spawn_enemies();
  }, Game.SPAWN_INTERVAL);

}).call(this);
